### ISSUE TITLE
Km calculation

### ISSUE THREAD

**Issue by iagsav** [bunnie/netv2-derive_km#1]
Hello! Using your code, we tried to calculate the Km value for the ksv specified on page 58 of this file: https://www.digital-cp.com/sites/default/files/specifications/HDCP%20Specification%20Rev1_4_Secure.pdf

The list of keys received by KSV also did not match

Please tell me what this may be related to?

**Comment by bunnie** [comment]
As the table is annotated, these are "facsimile keys for test purposes". iirc they are derived from a master key that is not the one that is used in production devices. This was done presumably in an attempt to keep the master key secure, because with sufficient numbers of test keys one could derive the master key by reversing the linear algebra.

The code published here uses the production master key, since it must interoperate with production hardware, and not test code.

**Comment by iagsav** [comment]
Thanks for the explanation!

**Comment by iagsav** [comment]
@bunnie maybe you have the calculated values of R0 and An for the test KSV given in the compute_ksv.c file? Can you provide them?

**Comment by bunnie** [comment]
Hmm, if I did it would have been ages ago -- this code is from over a decade ago. Ever since I moved to using production keys, that's all I've used for testing.

**Comment by iagsav** [comment]
@bunnie Thank you!
